Basic implementation of Onvif standard
glikely/obs-ptz pull request #94
Opened 2022-05-15 16:57 UTC by jonata

Related to #16

2022-05-16 04:29 UTC, pmichaud commented
FWIW, I can confirm that this pull request enables ONVIF PTZ to work for my IP camera (Amcrest IP2M-841B).     This is a great addition to obs-studio for me and I hope it can be pulled into the mainline soon!  If I can help with that, please let me know.

Pm

2022-05-16 04:40 UTC, jonata commented
Great to know, thanks for testing! One thing I was not able to verify if it's working is the absolute and relative moves, I think they are related to the "Presets" of the plugin. I think my camera does not support that. If someone could check that, it would be great. Hope it get merged to mainline soon. Thanks!

2022-05-21 15:00 UTC, michaeleino commented
for basic support it is really awesome...
it works with hikvision DS-2DF5220S-* but,
-presets is not working
- left/right is reversed ...left moves to right and right moves to left

2022-05-21 15:51 UTC, jonata commented
Thanks for testing! Yes, I based this code on my camera, and not sure if my camera's configuration are right. Maybe it's reversed in my case. So latest commit fixes that. Thanks again! About the absolute (presets), if you are running Linux, could you call obs from the terminal, test the presets, and save the output so I could check? Thanks!

2022-05-21 19:56 UTC, pmichaud commented
I can run from terminal and test presets on Monday in all likelihood; will report then.  It won't surprise me too much if the ONVIF <AbsoluteMove ...> isn't supported on cameras like my Amcrest ($50)... but for something more expensive like the Hikvision I'd kind of expect it to be there.  So, we'll see.

Left/right was also "reversed" on my Amcrest camera (prior to b5cc93d commit), but it's also a matter of interpretation as to what is "forward" and "reverse" so it's fine for me either way.

2022-05-22 12:23 UTC, michaeleino commented
thanks!
the reverse pan/tilt is correct now, i can't check the presets now, it just raises request timeout
```
Created new TCP socket 44 for connection
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
[PTZOnvif] Request timeout
```
just don't consider this logs, it is a remote connection... will test it on LAN connection by this Monday 

Thanks again!

2022-05-26 17:13 UTC, jonata commented
I discovered that the absolute and relative commands have nothing to do with the presets. The latest commits implement the internal PTZ preset settings. I tested with my camera and it's working. If someone else could test with other models it would be great. Thanks!!

2022-05-27 18:24 UTC, pmichaud commented
I can confirm that the presets now work on my Amcrest camera (as well as other fixes).

Thank you so much -- this is an awesome capability.  I've shown it to others who do similar work as I do and they're super-excited about it.

Pm

2022-05-28 11:03 UTC, michaeleino commented
i wasn't too lucky this time :(
it didn't work with hikvision, meanwhile there is logs this time

i wasn't too lucky this time :(
it didn't work with hikvision, meanwhile there is logs this time

> user@PC:~/Downloads/obs-ptz/build$ obs --verbose --unfiltered_log
Attempted path: share/obs/obs-studio/locale/en-US.ini
Attempted path: /usr/share/obs/obs-studio/locale/en-US.ini
Attempted path: share/obs/obs-studio/locale.ini
Attempted path: /usr/share/obs/obs-studio/locale.ini
Attempted path: share/obs/obs-studio/themes/Dark.qss
Attempted path: /usr/share/obs/obs-studio/themes/Dark.qss
info: Command Line Arguments: --verbose --unfiltered_log
info: CPU Name: Intel(R) Core(TM) i5-3340M CPU @ 2.70GHz
info: CPU Speed: 1200.000MHz
info: Physical Cores: 2, Logical Cores: 4
info: Physical Memory: 7825MB Total, 1138MB Free
info: Kernel Version: Linux 5.13.0-39-generic
info: Distribution: "Ubuntu" "20.04"
info: Session Type: x11
info: Window System: X11.0, Vendor: The X.Org Foundation, Version: 1.20.13
info: Qt Version: 5.12.8 (runtime), 5.12.8 (compiled)
info: Portable mode: false
Attempted path: share/obs/obs-studio/themes/Dark/no_sources.svg
Attempted path: /usr/share/obs/obs-studio/themes/Dark/no_sources.svg
QMetaObject::connectSlotsByName: No matching signal for on_tbar_position_valueChanged(int)
QMetaObject::connectSlotsByName: No matching signal for on_actionShowTransitionProperties_triggered()
QMetaObject::connectSlotsByName: No matching signal for on_actionHideTransitionProperties_triggered()
info: OBS 27.2.4 (linux)
info: ---------------------------------
info: ---------------------------------
info: audio settings reset:
	samples per sec: 48000
	speakers:        2
info: ---------------------------------
info: Initializing OpenGL...
info: Loading up OpenGL on adapter Intel Open Source Technology Center Mesa DRI Intel(R) HD Graphics 4000 (IVB GT2)
info: OpenGL loaded successfully, version 4.2 (Core Profile) Mesa 21.2.6, shading language 4.20
info: ---------------------------------
info: video settings reset:
	base resolution:   1366x768
	output resolution: 852x480
	downscale filter:  Bicubic
	fps:               30/1
	format:            NV12
	YUV mode:          709/Partial
info: NV12 texture support not available
info: Audio monitoring device:
	name: Default
	id: default
info: ---------------------------------
warning: No AJA devices found, skipping loading AJA UI plugin
warning: Failed to initialize module 'aja-output-ui.so'
warning: No AJA devices found, skipping loading AJA plugin
warning: Failed to initialize module 'aja.so'
warning: Failed to load 'en-US' text for module: 'decklink-captions.so'
warning: Failed to load 'en-US' text for module: 'decklink-ouput-ui.so'
libDeckLinkAPI.so: cannot open shared object file: No such file or directory
warning: A DeckLink iterator could not be created.  The DeckLink drivers may not be installed
info: No blackmagic support
warning: v4l2loopback not installed, virtual camera disabled
info: [obs-browser]: Version 2.17.13
info: [obs-browser]: CEF Version 95.0.0-MediaHandler.2463+g3b3ac84+chromium-95.0.4638.69
error: os_dlopen(libnvidia-encode.so.1->libnvidia-encode.so.1): libnvidia-encode.so.1: cannot open shared object file: No such file or directory
info: FFMPEG VAAPI supported
warning: Failed to load 'en-US' text for module: 'obs-multi-rtmp.so'
QWidget::setLayout: Attempting to set QLayout "" on QDockWidget "", which already has a layout
warning: Failed to load 'en-US' text for module: 'ptz-controls.so'
info: [ptz-controls] PTZ controller OBS Plugin"v0.10.4-17-g44e2c96"
info: [ptz-controls] gamepads changed
[PTZOnvif] Request onvif  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:tt=\"http://www.onvif.org/ver10/schema\"><s:Header><Security s:mustUnderstand=\"1\" xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><UsernameToken><Username>camuser</Username><Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">ReKkMvLFwxzEkaSngbLjluPj6xI=</Password><Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">ezZkOTk3YWZjLWMwOTItNDE2Mi1hYmU1LTViNjU4ZDI1ZDhiYn0=</Nonce><Created xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">2022-05-28T10:24:27Z</Created></UsernameToken></Security></s:Header><s:Body><tds:GetCapabilities><tds:Category>All</tds:Category></tds:GetCapabilities></s:Body></s:Envelope>"
[PTZOnvif] Request onvif  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:tt=\"http://www.onvif.org/ver10/schema\"><s:Header><Security s:mustUnderstand=\"1\" xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><UsernameToken><Username>camuser</Username><Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">H52NfgD0qwiYJti7pRBvggTI8xo=</Password><Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">ezEyY2IzZTkxLWZiNDMtNGNhOC1hMWRlLWMxNDdhY2IyZTVlNH0=</Nonce><Created xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">2022-05-28T10:24:27Z</Created></UsernameToken></Security></s:Header><s:Body><trt:GetProfiles/></s:Body></s:Envelope>"
[PTZOnvif] Connection success 
[PTZOnvif] Request onvif  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:tds=\"http://www.onvif.org/ver10/device/wsdl\" xmlns:tt=\"http://www.onvif.org/ver10/schema\"><s:Header><Security s:mustUnderstand=\"1\" xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><UsernameToken><Username>camuser</Username><Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">IuFv0khY2UbIWAIDDqujuGGG5HQ=</Password><Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">e2QyMzJlMmU3LTJhY2QtNDllZi04ODk1LTE5NWVkM2QxYmZmNH0=</Nonce><Created xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">2022-05-28T10:24:27Z</Created></UsernameToken></Security></s:Header><s:Body><tds:GetCapabilities><tds:Category>All</tds:Category></tds:GetCapabilities></s:Body></s:Envelope>"
[PTZOnvif] Request onvif  "<?xml version=\"1.0\" encoding=\"UTF-8\"?><s:Envelope xmlns:s=\"http://www.w3.org/2003/05/soap-envelope\" xmlns:trt=\"http://www.onvif.org/ver10/media/wsdl\" xmlns:tt=\"http://www.onvif.org/ver10/schema\"><s:Header><Security s:mustUnderstand=\"1\" xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-secext-1.0.xsd\"><UsernameToken><Username>camuser</Username><Password Type=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-username-token-profile-1.0#PasswordDigest\">niKOVMtwsn6e8kZor1GH/qawFxE=</Password><Nonce EncodingType=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-soap-message-security-1.0#Base64Binary\">ezM2ZTc3YWEwLTY3ZTktNGY3MS04YjIxLTg4Nzg4MGYxNTJhNX0=</Nonce><Created xmlns=\"http://docs.oasis-open.org/wss/2004/01/oasis-200401-wss-wssecurity-utility-1.0.xsd\">2022-05-28T10:24:27Z</Created></UsernameToken></Security></s:Header><s:Body><trt:GetProfiles/></s:Body></s:Envelope>"
[PTZOnvif] Connection success 
info: [vlc-video]: VLC 3.0.9.2 Vetinari found, VLC video source enabled
info: ---------------------------------
info:   Loaded Modules:
info:     vlc-video.so
info:     text-freetype2.so
info:     rtmp-services.so
info:     ptz-controls.so
info:     obs-x264.so
info:     obs-vst.so
info:     obs-transitions.so
info:     obs-outputs.so
info:     obs- [...]

2022-05-28 15:24 UTC, jonata commented
@michaeleino , I see on the log that your camera seems to support the presets. Tell me what is not working, is it the movement (when you click on the arrows) or the presets? If the presets are not working, make sure you are using it in the way it's intended to work. You need to first "save preset" in a specific position. Do this in various presets, and then you double click on the preset so it will call the camera to access that specific preset. I see your camera have a lot of presets, but none of them were "created" by obs-ptz.

2022-05-29 03:18 UTC, pmichaud commented
A key note might be "double click on the preset".  It confused me for a bit until I discovered that single-click on a preset wouldn't activate it -- a double-click is needed.

Pm

2022-05-30 16:52 UTC, michaeleino commented
@jonata aaaagh ... okay i was confused on how it works, AFAIK i thought it will retrieve and call the preset saved on the camera :D 
but this doesn't happen... it works when I set a position and right-click > save preset 
may be this is somewhere on the docs but i couldn't find.

overall, it is really great and amazing 

many many thanks !

@pmichaud yup noted, thanks :)

2022-05-30 16:53 UTC, michaeleino commented
hope to see this pr the soonest on the next release,,, I have issues to compile on windows :(

2022-05-30 19:08 UTC, jonata commented
Hi @michaeleino, glad that it worked for you. Yes, I also thought that it would be possible to access presets previously saved in the camera, but the way the plugin is working right now, that's not possible. You need to save the preset on the plugin before.

2022-07-20 15:58 UTC, glikely requested changes
Hi Jonata,

Thanks for writing this driver! I've wanted to get ONVIF support into the plugin, but haven't had time to work on it, and I don't have any ONVIF devices to test againts.

I've made a number of comments through the code. Please take a read through. The biggest functional feedback I have is that the code needs to be made non-blocking. All of the PTZ functionality runs in the UI main thread, so any calls to `.mdelay()`, or creating a new event loop will stall the UI until the camera responds. You'll need to track state in the PTZOnvif object so that it can keep track of what events are in-flight and handle them appropriately.

Regarding pull requests, I need two things before I merge changes: good commit messages that describe the change, and a DCO Signed-off-by: line. See [CONTRIBUTING.md](/glikely/obs-ptz/blob/main/CONTRIBUTING.md) for what this means. I'm an old Linux engineer, and process habits die hard. :-) Seriously though, I've learned that good contribution process avoids problems down the road and makes it easier to see how the project has evolved.

For future changes from you I'll be strict about this. However, for this PR I'm happy to pull the code into mainline now if you go and read CONTRIBUTING.md, and then reply on this thread with `Signed-off-by: Your Name <youremail>`. I won't include it in any releases yet though because the comments I've left do need to be addressed.

Once again, thanks for doing this work, and I look forward to seeing the next iteration.

2022-07-20 16:10 UTC, jonata commented
Hey @glikely , thank you so much for considering this PR. I am so sorry about the poor code, as I am definitely not a C++ developer, I just code in Python, so I expected this code far from being ideal. It's an adaptation from other pieces of code I learn elsewhere. So I really really appreciate your review and feedback, so I can learn more about this language and best practices. I will review and try to address the issues. Thanks again!

2022-07-20 16:10 UTC, jonata commented
Signed-off-by: Jonatã Bolzan Loss <jonata@jonata.org>

2022-07-20 16:22 UTC, glikely commented
No worries. I'm a C developer myself, and had to do a lot of work to come up to speed on C++ for this project

2022-07-22 14:22 UTC, glikely commented
I've cleaned up the indentation and order of the code and cleaned up some of the minor coding conventions issues. The results has been pushed out to the main branch. However, I've disabled the creation of ONVIF devices in settings until the blocking issues are resolved. I'll leave it to you to rework from here.

2022-07-22 14:22 UTC, closed without merging